import { EligibilityCategory, EligibilityCatalogItem } from '@/types/eligibility';

export const ELIGIBILITY_CATALOG: EligibilityCategory[] = [
  {
    id: 'financial',
    label: 'Financial Assistance',
    items: [
      {
        type: 'snap_ebt',
        label: 'SNAP / EBT (Museums for All)',
        icon: '🏛️',
        description: 'Free or reduced admission at 900+ museums nationwide',
      },
    ],
  },
  {
    id: 'bank',
    label: 'Bank & Cardholder Programs',
    items: [
      {
        type: 'bofa_museums_on_us',
        label: 'Bank of America — Museums on Us',
        icon: '💳',
        description: 'Free admission on the first full weekend of each month',
      },
    ],
  },
  {
    id: 'student',
    label: 'Student',
    items: [
      {
        type: 'student',
        label: 'Student ID',
        icon: '🎓',
        description: 'Student discount with valid school ID',
        hasDetails: 'schools',
      },
    ],
  },
  {
    id: 'military',
    label: 'Military & Service',
    items: [
      {
        type: 'military',
        label: 'Active Duty / Veteran',
        icon: '🎖️',
        description: 'Military discount for active duty and veterans',
      },
      {
        type: 'blue_star',
        label: 'Blue Star Museums',
        icon: '⭐',
        description: 'Free admission for active duty military families',
      },
    ],
  },
  {
    id: 'library',
    label: 'Library & City Programs',
    items: [
      {
        type: 'library_pass',
        label: 'Library Card / Museum Pass',
        icon: '📚',
        description: 'Free or discounted passes through your library',
        hasDetails: 'libraries',
      },
      {
        type: 'city_id',
        label: 'City ID / Local Cultural Program',
        icon: '🏙️',
        description: 'Local cultural access programs',
      },
    ],
  },
  {
    id: 'membership',
    label: 'Memberships & Reciprocity',
    items: [
      {
        type: 'icom',
        label: 'ICOM Member',
        icon: '🌐',
        description: 'International Council of Museums membership',
      },
      {
        type: 'reciprocal_museum',
        label: 'Reciprocal Museum Membership',
        icon: '🔄',
        description: 'Reciprocal admission at partner museums',
      },
      {
        type: 'science_reciprocity',
        label: 'Science Center Reciprocity',
        icon: '🔬',
        description: 'ASTC-style reciprocal science center admission',
      },
    ],
  },
  {
    id: 'employer',
    label: 'Employer Benefits',
    items: [
      {
        type: 'employer',
        label: 'Company Employee / Corporate Partner',
        icon: '🏢',
        description: 'Employee benefits or corporate museum partnerships',
        hasDetails: 'companies',
      },
    ],
  },
  {
    id: 'other',
    label: 'Other Common Audiences',
    items: [
      {
        type: 'teacher',
        label: 'Teacher / Educator',
        icon: '📝',
        description: 'Educator discount with valid ID',
      },
      {
        type: 'first_responder',
        label: 'First Responder',
        icon: '🚒',
        description: 'Discount for first responders',
      },
      {
        type: 'senior',
        label: 'Senior',
        icon: '👤',
        description: 'Senior discount (age varies by museum)',
      },
      {
        type: 'local_resident',
        label: 'Local Resident',
        icon: '🏠',
        description: 'Discounts for local residents',
      },
    ],
  },
];

export const ALL_CATALOG_ITEMS: EligibilityCatalogItem[] = ELIGIBILITY_CATALOG.flatMap(c => c.items);

// Common schools for searchable dropdown
export const COMMON_SCHOOLS = [
  'Arizona State University',
  'Boston University',
  'Brown University',
  'California Institute of Technology',
  'Carnegie Mellon University',
  'Columbia University',
  'Cornell University',
  'Dartmouth College',
  'Duke University',
  'Emory University',
  'Georgetown University',
  'Georgia Institute of Technology',
  'Harvard University',
  'Indiana University',
  'Johns Hopkins University',
  'Massachusetts Institute of Technology',
  'Michigan State University',
  'New York University',
  'Northeastern University',
  'Northwestern University',
  'Ohio State University',
  'Oregon State University',
  'Penn State University',
  'Princeton University',
  'Purdue University',
  'Rice University',
  'Rutgers University',
  'Stanford University',
  'Syracuse University',
  'Texas A&M University',
  'Tufts University',
  'Tulane University',
  'University of California, Berkeley',
  'University of California, Los Angeles',
  'University of California, San Diego',
  'University of Chicago',
  'University of Colorado Boulder',
  'University of Florida',
  'University of Illinois Urbana-Champaign',
  'University of Maryland',
  'University of Michigan',
  'University of Minnesota',
  'University of North Carolina at Chapel Hill',
  'University of Notre Dame',
  'University of Pennsylvania',
  'University of Pittsburgh',
  'University of Southern California',
  'University of Texas at Austin',
  'University of Virginia',
  'University of Washington',
  'University of Wisconsin-Madison',
  'Vanderbilt University',
  'Virginia Tech',
  'Wake Forest University',
  'Washington University in St. Louis',
  'Yale University',
];

// Common library systems
export const COMMON_LIBRARIES = [
  'Brooklyn Public Library',
  'Chicago Public Library',
  'Cleveland Public Library',
  'Dallas Public Library',
  'Denver Public Library',
  'Detroit Public Library',
  'Free Library of Philadelphia',
  'Hennepin County Library',
  'Houston Public Library',
  'King County Library System',
  'Los Angeles Public Library',
  'Miami-Dade Public Library System',
  'Multnomah County Library',
  'New York Public Library',
  'Phoenix Public Library',
  'Queens Public Library',
  'San Antonio Public Library',
  'San Diego Public Library',
  'San Francisco Public Library',
  'San Jose Public Library',
  'Seattle Public Library',
];

// Common large employers
export const COMMON_EMPLOYERS = [
  'Accenture',
  'Adobe',
  'Airbnb',
  'Alphabet / Google',
  'Amazon',
  'American Express',
  'Apple',
  'AT&T',
  'Bank of America',
  'Boeing',
  'Capital One',
  'Cisco',
  'Citigroup',
  'Comcast',
  'Costco',
  'Deloitte',
  'Disney',
  'DoorDash',
  'eBay',
  'Ernst & Young (EY)',
  'Facebook / Meta',
  'General Electric',
  'General Motors',
  'Goldman Sachs',
  'IBM',
  'Intel',
  'Intuit',
  'JPMorgan Chase',
  'Johnson & Johnson',
  'KPMG',
  'LinkedIn',
  'Lockheed Martin',
  'Lyft',
  'McKinsey & Company',
  'Microsoft',
  'Morgan Stanley',
  'Netflix',
  'Nike',
  'NVIDIA',
  'Oracle',
  'PayPal',
  'Pfizer',
  'Procter & Gamble',
  'PwC',
  'Qualcomm',
  'Salesforce',
  'Samsung',
  'SAP',
  'Snap Inc.',
  'Spotify',
  'Starbucks',
  'Stripe',
  'T-Mobile',
  'Tesla',
  'Twitter / X',
  'Uber',
  'UnitedHealth Group',
  'Verizon',
  'Visa',
  'Walmart',
  'Wells Fargo',
];
