// Pre-populated searchable lists for eligibility detail editors
// Schools include flag emojis and cover Global Top 100+

export const COMMON_SCHOOLS = [
  '🇺🇸 Arizona State University',
  '🇦🇺 Australian National University',
  '🇺🇸 Boston University',
  '🇺🇸 Brown University',
  '🇺🇸 California Institute of Technology',
  '🇨🇦 University of British Columbia',
  '🇬🇧 University of Cambridge',
  '🇺🇸 Carnegie Mellon University',
  '🇨🇳 Tsinghua University',
  '🇨🇳 Peking University',
  '🇨🇳 Fudan University',
  '🇨🇳 Shanghai Jiao Tong University',
  '🇨🇳 Zhejiang University',
  '🇺🇸 Columbia University',
  '🇺🇸 Cornell University',
  '🇺🇸 Dartmouth College',
  '🇺🇸 Duke University',
  '🇨🇭 ETH Zurich',
  '🇨🇭 EPFL',
  '🇺🇸 Emory University',
  '🇺🇸 Georgetown University',
  '🇺🇸 Georgia Institute of Technology',
  '🇺🇸 Harvard University',
  '🇭🇰 University of Hong Kong',
  '🇭🇰 Chinese University of Hong Kong',
  '🇭🇰 Hong Kong University of Science and Technology',
  '🇮🇳 Indian Institute of Technology Bombay',
  '🇮🇳 Indian Institute of Technology Delhi',
  '🇮🇳 Indian Institute of Science',
  '🇺🇸 Indiana University',
  '🇺🇸 Johns Hopkins University',
  '🇯🇵 University of Tokyo',
  '🇯🇵 Kyoto University',
  '🇯🇵 Tokyo Institute of Technology',
  '🇯🇵 Osaka University',
  '🇰🇷 Seoul National University',
  '🇰🇷 KAIST',
  '🇰🇷 Yonsei University',
  '🇳🇱 University of Amsterdam',
  '🇳🇱 Delft University of Technology',
  '🇬🇧 Imperial College London',
  '🇬🇧 University College London',
  '🇬🇧 London School of Economics',
  '🇬🇧 King\'s College London',
  '🇬🇧 University of Edinburgh',
  '🇬🇧 University of Manchester',
  '🇬🇧 University of Oxford',
  '🇺🇸 Massachusetts Institute of Technology',
  '🇨🇦 McGill University',
  '🇦🇺 University of Melbourne',
  '🇺🇸 Michigan State University',
  '🇫🇷 Sorbonne University',
  '🇫🇷 PSL University',
  '🇫🇷 École Polytechnique',
  '🇩🇪 Technical University of Munich',
  '🇩🇪 Ludwig Maximilian University of Munich',
  '🇩🇪 Heidelberg University',
  '🇩🇪 Humboldt University of Berlin',
  '🇺🇸 New York University',
  '🇺🇸 Northeastern University',
  '🇺🇸 Northwestern University',
  '🇺🇸 Ohio State University',
  '🇺🇸 Oregon State University',
  '🇺🇸 Penn State University',
  '🇺🇸 Princeton University',
  '🇺🇸 Purdue University',
  '🇺🇸 Rice University',
  '🇺🇸 Rutgers University',
  '🇸🇬 National University of Singapore',
  '🇸🇬 Nanyang Technological University',
  '🇺🇸 Stanford University',
  '🇸🇪 KTH Royal Institute of Technology',
  '🇺🇸 Syracuse University',
  '🇺🇸 Texas A&M University',
  '🇨🇦 University of Toronto',
  '🇺🇸 Tufts University',
  '🇺🇸 Tulane University',
  '🇺🇸 University of California, Berkeley',
  '🇺🇸 University of California, Los Angeles',
  '🇺🇸 University of California, San Diego',
  '🇺🇸 University of California, San Francisco',
  '🇺🇸 University of California, Santa Barbara',
  '🇺🇸 University of Chicago',
  '🇺🇸 University of Colorado Boulder',
  '🇺🇸 University of Florida',
  '🇺🇸 University of Illinois Urbana-Champaign',
  '🇺🇸 University of Maryland',
  '🇺🇸 University of Michigan',
  '🇺🇸 University of Minnesota',
  '🇺🇸 University of North Carolina at Chapel Hill',
  '🇺🇸 University of Notre Dame',
  '🇺🇸 University of Pennsylvania',
  '🇺🇸 University of Pittsburgh',
  '🇺🇸 University of Southern California',
  '🇺🇸 University of Texas at Austin',
  '🇺🇸 University of Virginia',
  '🇺🇸 University of Washington',
  '🇺🇸 University of Wisconsin-Madison',
  '🇺🇸 Vanderbilt University',
  '🇺🇸 Virginia Tech',
  '🇺🇸 Wake Forest University',
  '🇺🇸 Washington University in St. Louis',
  '🇨🇦 University of Waterloo',
  '🇦🇺 University of Sydney',
  '🇦🇺 University of New South Wales',
  '🇦🇺 Monash University',
  '🇧🇷 University of São Paulo',
  '🇮🇱 Hebrew University of Jerusalem',
  '🇮🇱 Technion - Israel Institute of Technology',
  '🇺🇸 Yale University',
];

// Common library systems
export const COMMON_LIBRARIES = [
  'Brooklyn Public Library',
  'Chicago Public Library',
  'Cleveland Public Library',
  'Dallas Public Library',
  'Denver Public Library',
  'Detroit Public Library',
  'Free Library of Philadelphia',
  'Hennepin County Library',
  'Houston Public Library',
  'King County Library System',
  'Los Angeles Public Library',
  'Miami-Dade Public Library System',
  'Multnomah County Library',
  'New York Public Library',
  'Phoenix Public Library',
  'Queens Public Library',
  'San Antonio Public Library',
  'San Diego Public Library',
  'San Francisco Public Library',
  'San Jose Public Library',
  'Seattle Public Library',
];

// Common large employers
export const COMMON_EMPLOYERS = [
  'Accenture',
  'Adobe',
  'Airbnb',
  'Alphabet / Google',
  'Amazon',
  'American Express',
  'Apple',
  'AT&T',
  'Bank of America',
  'Boeing',
  'Capital One',
  'Cisco',
  'Citigroup',
  'Comcast',
  'Costco',
  'Deloitte',
  'Disney',
  'DoorDash',
  'eBay',
  'Ernst & Young (EY)',
  'Facebook / Meta',
  'General Electric',
  'General Motors',
  'Goldman Sachs',
  'IBM',
  'Intel',
  'Intuit',
  'JPMorgan Chase',
  'Johnson & Johnson',
  'KPMG',
  'LinkedIn',
  'Lockheed Martin',
  'Lyft',
  'McKinsey & Company',
  'Microsoft',
  'Morgan Stanley',
  'Netflix',
  'Nike',
  'NVIDIA',
  'Oracle',
  'PayPal',
  'Pfizer',
  'Procter & Gamble',
  'PwC',
  'Qualcomm',
  'Salesforce',
  'Samsung',
  'SAP',
  'Snap Inc.',
  'Spotify',
  'Starbucks',
  'Stripe',
  'T-Mobile',
  'Tesla',
  'Twitter / X',
  'Uber',
  'UnitedHealth Group',
  'Verizon',
  'Visa',
  'Walmart',
  'Wells Fargo',
];
